### ISSUE TITLE
cant reload

### ISSUE THREAD

**Issue by bobyjones** [bensku/Skript#789]
I don't know whats going on but if I reload scripts or all it gives me an error

> [21:19:48 INFO]: bobyjones issued server command: /sk reload all
> [21:19:49 ERROR]: null
> org.bukkit.command.CommandException: Unhandled exception executing command 'sk' in plugin Skript v2.2-dev30b
>         at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
>         at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
>         at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
>         at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
>         at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
>         at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
>         at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
>         at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
>         at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
>         at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
>         at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
>         at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
>         at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
>         at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
> Caused by: java.lang.NoSuchMethodError: ch.njol.skript.command.Commands.loadCommand(Lch/njol/skript/config/SectionNode;Z)Lch/njol/skript/command/ScriptCommand;
>         at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:526) ~[?:?]
>         at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:333) ~[?:?]
>         at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:345) ~[?:?]
>         at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:275) ~[?:?]
>         at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:305) ~[?:?]
>         at ch.njol.skript.Skript.reload(Skript.java:701) ~[?:?]
>         at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:161) ~[?:?]
>         at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
>         ... 15 more

**Comment by TheBentoBox** [comment]
This fork doesn't support versions below 1.9. You can try downgrading to dev25 as it was the last version that worked on 1.8 but we can't provide any further support.
